name: Validate Project Metadata

on:
  pull_request:
    paths:
      - 'project.yaml'
      - 'maintainers.yaml'
  push:
    branches: [main]
    paths:
      - 'project.yaml'
      - 'maintainers.yaml'
  workflow_dispatch:

jobs:
  validate-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: cncf/automation/.github/actions/validate-project@b2b25cfa5ab1ed19617a4d864dafaf9b1b894690
        with:
          project_file: 'project.yaml'

  validate-maintainers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: cncf/automation/.github/actions/validate-maintainers@b2b25cfa5ab1ed19617a4d864dafaf9b1b894690
        with:
          maintainers_file: 'maintainers.yaml'
          # Disabled until the LFX LLT issue is resolved. Validation is done manually for now.
          verify_maintainers: 'false'
        env:
          LFX_AUTH_TOKEN: ${{ secrets.LFX_AUTH_TOKEN }}
